name: Docker Build, Run and Push

on: [workflow_dispatch]

env:
  IMAGE_NAME: workflow-run-number-tag

jobs:
  build-and-push:
  
    runs-on: ubuntu-latest
    permissions:
     contents: write
     packages: write

    steps:
    - name: code checkout
      uses: actions/checkout@v4
      
    - name: setup jdk 17
      uses: actions/setup-java@4
       java-version:'17'
       distribution:'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/workflow-run-number-tag:latest
          ghcr.io/${{ github.repository_owner }}/workflow-run-number-tag:${{ github.run_number }}

     
     
